---

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
# 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored)
# 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
# 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
# 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
# 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
# 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
# 1.1.1.8 Ensure mounting of FAT filesystems is disabled (Scored)
- name: Remove unneeded filesystem kernel module
  modprobe:
    name:  "{{ item.name }}"
    state: absent
  with_items: "{{ os_hardening_fs_modules_disable }}"
  when: item.cis_id not in os_hardening_exclusions
  tags:
    - scored
    - 1.1.1.1
    - 1.1.1.2
    - 1.1.1.3
    - 1.1.1.4
    - 1.1.1.5
    - 1.1.1.6
    - 1.1.1.7
    - 1.1.1.8

- name: Disable mounting of unneeded filesystems
  template:
    src:   modules-disable.conf.j2
    dest:  /etc/modprobe.d/CIS.conf
    owner: root
    group: root
    mode:  0644
  tags:
    - scored
    - 1.1.1.1
    - 1.1.1.2
    - 1.1.1.3
    - 1.1.1.4
    - 1.1.1.5
    - 1.1.1.6
    - 1.1.1.7
    - 1.1.1.8


# 1.1.2 Ensure separate partition exists for /tmp (Scored)
# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
# 1.1.5 Ensure separate partition exists for /var (Scored)
# 1.1.6 Ensure separate partition exists for /var/tmp (Scored)
# 1.1.7 Ensure nodev option set on /var/tmp partition (Scored)
# 1.1.8 Ensure nosuid option set on /var/tmp partition (Scored)
# 1.1.9 Ensure noexec option set on /var/tmp partition (Scored)
# 1.1.10 Ensure separate partition exists for /var/log (Scored)
# 1.1.11 Ensure separate partition exists for /var/log/audit (Scored)
# 1.1.12 Ensure separate partition exists for /home (Scored)
# 1.1.13 Ensure nodev option set on /home partition (Scored)
# 1.1.14 Ensure nodev option set on /run/shm partition (Scored)
# 1.1.15 Ensure nosuid option set on /run/shm partition (Scored)
# 1.1.16 Ensure noexec option set on /run/shm partition (Scored)
# 1.1.17 Ensure nodev option set on removable media partitions (Not Scored)
# 1.1.18 Ensure nosuid option set on removable media partitions (Not Scored)
# 1.1.19 Ensure noexec option set on removable media partitions (Not Scored)

- debug: msg='1.1.2 - 1.1.19 | Not Implemented as they relate to filesystem partitions and mount options that require out of bound config'


# 1.1.20 Ensure sticky bit is set on all world-writable directories (Scored)
- name: Set the sticky bit on all world writable directories
  shell: >
      df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  when: "'1.1.20' not in os_hardening_exclusions"
  tags:
    - scored
    - 1.1.20


# 1.1.21 Disable Automounting (Scored)
- name: Check if /etc/init/autofs.conf exists
  stat:
    path: /etc/init/autofs.conf
  register: autofs
  tags:
    - scored
    - 1.1.21

- name: Comment out start lines in /etc/init/autofs.conf
  lineinfile:
    path: /etc/init/autofs.conf
    regexp: '^start on runlevel'
    line: '#start on runlevel [2345]'
  when: "'1.1.21' not in os_hardening_exclusions and autofs.stat.exists"
  tags:
    - scored
    - 1.1.21
